### ISSUE TITLE
发送心跳包失败怎么回事？

### ISSUE THREAD

**Issue by brighill** [coverxit/EasyDrcomGUI#1]
> 2016-04-10 22:54:15 [EAP Debug] Recevied after Start, eapol_type = 0x0, eap_id = 0x1, eap_type = 0x1, eap_length = 500
> 2016-04-10 22:54:15 [EAP Info] Gateway returns: Request, Identity
> 2016-04-10 22:54:15 [EAP Info] Response, Identity.
> 2016-04-10 22:54:16 [EAP Debug] Recevied after Response, Identity, eapol_type = 0x0, eap_id = 0x0, eap_type = 0x4, eap_length = 1a00
> 2016-04-10 22:54:16 [EAP Info] Gateway returns: Request, MD5-Challenge EAP
> 2016-04-10 22:54:16 [EAP Info] Response, MD5-Challenge EAP.
> 2016-04-10 22:54:17 [EAP Debug] Recevied after Response, MD5-Challenge EAP, eapol_type = 0x0, eap_id = 0x0, eap_type = 0x0, eap_length = 400
> 2016-04-10 22:54:17 [EAP Info] Gateway returns: Success
> 2016-04-10 22:54:17 [U62 Info] Send Alive Packet 1.
> 2016-04-10 22:54:17 [U62 Debug] send packet data dump:
> 00000000: 07 00 28 00 0b 01 1f 00  00 00 00 00 00 00 00 00  ..(.............
> 00000010: 00 00 00 00 00 00 00 00  00 00 00 00 00 00 00 00  ................
> 00000020: 00 00 00 00 00 00 00 00      

有人吗？ @coverxit

**Comment by coverxit** [comment]
你发的这段日志里面看不出错误
