### ISSUE TITLE
感谢你写的EasyDrcomGUI～

### ISSUE THREAD

**Issue by HowquaX** [coverxit/EasyDrcomGUI#2]
我基于它写了能在另外一个学校用的版本~

**Comment by coverxit** [comment]
@HowquaX Glad to see that~~ XD
Any modifications in the authentication modules?
If any, would you like to release the source code?
We all will appreciate it!

**Comment by HowquaX** [comment]
Yes, I have modified the authentication modules in order to support the U31 that is using in GDUFE.
I have already uploaded the source code in Github.

**Comment by HowquaX** [comment]
https://github.com/HowquaX/EasyDrcomGUI-For-GDUFE

**Comment by coverxit** [comment]
@HowquaX 感谢为突破Dr.COM做出的贡献~ （终于找到一台有中文输入法的设备XD
