### ISSUE TITLE
win10建议使用npcap

### ISSUE THREAD

**Issue by Rprop** [coverxit/EasyDrcomGUI#3]
win10pcap某些情况下不稳定, npcap相比更优同时持续更新中(winpcap兼容模式安装)

**Comment by coverxit** [comment]
got it.

**Comment by hsluoyz** [comment]
Hi. I'm the author of [Npcap](https://github.com/nmap/npcap). Welcome to use Npcap! Npcap has published hundreds of releases to make it a more stable and promising replacement for WinPcap than Win10Pcap.

You can download Npcap at: https://github.com/nmap/npcap/releases
If there's any questions or issues during using it, please let me know!

**Comment by coverxit** [comment]
@hsluoyz I'll give it a try. Seems that npcap is integrated with libpcap?

**Comment by hsluoyz** [comment]
@coverxit Yes, Npcap supports the latest Libpcap 1.8.1. The benefit is that you can use the same version Libpcap API on all platforms such as Linux, Windows and even macOS.
